{% set version = "0.5.5" %}

package:
  name: axiprop
  version: {{ version }}

source:
  url: https://github.com/hightower8083/axiprop/archive/refs/tags/{{ version }}.tar.gz
  sha256: 464c3f4db29f99f5d58151ac8883e718e5d29746ba601b106e4d9950dc749a59

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy
    - h5py
    - python >={{ python_min }}
    - scipy

test:
  requires:
    - python {{ python_min }}
    - pytest
    - scikit-image
  source_files:
    - tests/
  imports:
    - axiprop

about:
  home: https://github.com/hightower8083/axiprop
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "A simple-to-use optical propagation tool"

  description: |
    A simple tool to compute optical propagation, based on the discrete Hankel and Fourier transforms.
  dev_url: https://github.com/hightower8083/axiprop

extra:
  recipe-maintainers:
    - ax3l
    - hightower8083
