{% set version = "0.5.2" %}

package:
  name: axiprop
  version: {{ version }}

source:
  url: https://github.com/hightower8083/axiprop/archive/refs/tags/{{ version }}.tar.gz
  sha256: 60c35fa42b5d887aad6c241fc22fcd57df94e8ef8912de0a2f57443a8292b43c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - numpy
    - python >=3.6
    - scipy

test:
  requires:
    - python
    - pytest
    - scikit-image
  source_files:
    - tests/
  imports:
    - axiprop

about:
  home: https://github.com/hightower8083/axiprop
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "A simple-to-use optical propagation tool"

  description: |
    A simple tool to compute optical propagation, based on the discrete Hankel and Fourier transforms.
  dev_url: https://github.com/hightower8083/axiprop

extra:
  recipe-maintainers:
    - ax3l
    - hightower8083
